name: Maven CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pull-request-pre-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: validate-github-repository
        run: echo "Repository has passed compliance rules"
      - name: validate-commit-rules
        run: echo "Commit message and association to valid ticket"

  build:
    needs: pull-request-pre-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

